[cpu]
active = true
period = 60
threshold = 95

[memory]
active = true
period = 300
threshold = 90

[disk]
active = true
period = 300
threshold = 90

[status_update]
active = true
at_time = "7:30" 

[logging]
file_path = "usage.log"



